/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LiveLoad;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        DirWatch dirWatch = new DirWatch("/Users/thomaspetty/Desktop");
        dirWatch.start(); //start() makes now thread
        System.out.println(new App().getGreeting());
    }
}